apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-user-data-pv
spec:
  capacity:
    storage: {{ .Values.global.pv.capacity }}
  accessModes:
    {{- range .Values.global.pv.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.global.nfs.path }}
    server: {{ .Values.global.nfs.server }}
