apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-terminal
  namespace: sec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-terminal
  template:
    metadata:
      labels:
        app: gotty-terminal
    spec:
      containers:
      - name: gotty-terminal
        image: dclinics/sec-labs:v3
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /user_sessions
          name: session-storage
        env:
        - name: GOTTY_USER
          value: "nonroot"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: session-storage
        persistentVolumeClaim:
          claimName: user-session-pvc


---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gotty-terminal-service
  namespace: sec
spec:
  selector:
    app: gotty-terminal
  ports:
    - protocol: TCP
      port: 8080    # Exposed port
      targetPort: 8080  # Container port
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gotty-config
  namespace: sec
data:
  GOTTY_USER: "appuser"  # Replace appuser with your desired username
