apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-terminal
  namespace: sec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-terminal
  template:
    metadata:
      labels:
        app: gotty-terminal
    spec:
      containers:
      - name: gotty-terminal
        image: dclinics/sec-labs:v3.46
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gotty-config  # Pass the GOTTY_USER environment variable
        volumeMounts:
        - mountPath: /user_sessions
          name: session-storage
        - mountPath: /etc/sudoers.d
          name: sudoers-volume  # Mount sudoers directory
        command:
          - /bin/bash
          - -c
          - |
            # Install necessary packages and create user
            apt-get update && apt-get install -y sudo
            # Use the GOTTY_USER environment variable from the ConfigMap
            if [ -n "$GOTTY_USER" ]; then
              echo "Creating user ${GOTTY_USER}..."
              useradd -m -s /bin/bash ${GOTTY_USER} && \
              echo "${GOTTY_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${GOTTY_USER} && \
              id ${GOTTY_USER} || exit 1
            fi
            # Start GoTTY as the created user
            exec gosu ${GOTTY_USER} /usr/local/bin/gotty --permit-write --reconnect /bin/bash
      volumes:
      - name: session-storage
        persistentVolumeClaim:
          claimName: user-session-pvc
      - name: sudoers-volume
        emptyDir: {}  # Empty directory to mount sudoers directory



---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gotty-terminal-service
  namespace: sec
spec:
  selector:
    app: gotty-terminal
  ports:
    - protocol: TCP
      port: 8080    # Exposed port
      targetPort: 8080  # Container port
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gotty-config
  namespace: sec
data:
  GOTTY_USER: "appuser"  # Replace appuser with your desired username
