apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-terminal
  namespace: sec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-terminal
  template:
    metadata:
      labels:
        app: gotty-terminal
    spec:
      initContainers:
      - name: init-user
        image: ubuntu:latest  # Use an image with basic utilities like useradd
        command:
          - /bin/bash
          - -c
          - |
            apt-get update && apt-get install -y sudo
            useradd -m -s /bin/bash ${GOTTY_USER}
            echo "${GOTTY_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${GOTTY_USER}
        envFrom:
          - configMapRef:
              name: gotty-config
        securityContext:
          runAsUser: 0  # Run the init container as root to create the user

      containers:
      - name: gotty-terminal
        image: dclinics/sec-labs:v3.43
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gotty-config  # Pass the GOTTY_USER environment variable
        volumeMounts:
        - mountPath: /user_sessions
          name: session-storage
        - mountPath: /etc/sudoers.d
          name: sudoers-volume  # Mount sudoers directory to avoid permission issues

      volumes:
      - name: session-storage
        persistentVolumeClaim:
          claimName: user-session-pvc
      - name: sudoers-volume
        emptyDir: {}  # Empty directory to mount the sudoers directory to avoid conflicts



---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gotty-terminal-service
  namespace: sec
spec:
  selector:
    app: gotty-terminal
  ports:
    - protocol: TCP
      port: 8080    # Exposed port
      targetPort: 8080  # Container port
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gotty-config
  namespace: sec
data:
  GOTTY_USER: "appuser"  # Replace appuser with your desired username
