apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-server
  labels:
    app: ubuntu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-server
  template:
    metadata:
      labels:
        app: ubuntu-server
    spec:
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: ubuntu-pvc
      containers:
        - name: sec-labs
          image: dclinics/sec-labs:v1
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /home/users
              name: user-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-server-service
  labels:
    app: ubuntu-server
spec:
  selector:
    app: ubuntu-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 22
  type: ClusterIP