---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-backend
  namespace: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-backend
  template:
    metadata:
      labels:
        app: gotty-backend
    spec:
      containers:
      - name: backend
        image: dclinics/sec-bk:v1.12
        command: ["python"]
        args: ["backend.py"]
        volumeMounts:
        - name: gotty-pvc-storage
          mountPath: /data
        ports:
        - containerPort: 5000
      volumes:
      - name: gotty-pvc-storage
        persistentVolumeClaim:
          claimName: gotty-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-frontend
  namespace: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-frontend
  template:
    metadata:
      labels:
        app: gotty-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:latest
        volumeMounts:
        - name: frontend-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: frontend-files
        configMap:
          name: gotty-frontend-files
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-terminal
  namespace: v3
spec:
  replicas: 1  # Adjust dynamically for each user session
  selector:
    matchLabels:
      app: gotty-terminal
  template:
    metadata:
      labels:
        app: gotty-terminal
    spec:
      containers:
      - name: gotty
        image: dclinics/sec-labs:v2
        command: ["/usr/local/bin/gotty"]
        args: ["--permit-write", "--reconnect", "/bin/bash"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: user-data
          mountPath: /data  # Persistent user session data
      volumes:
      - name: user-data
        persistentVolumeClaim:
          claimName: gotty-pvc
