---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-terminal
  namespace: terminal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-terminal
  template:
    metadata:
      labels:
        app: gotty-terminal
    spec:
      containers:
      - name: gotty-terminal
        image: dclinics/sec-labs:v2
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/user_sessions"
          name: session-storage
      volumes:
      - name: session-storage
        persistentVolumeClaim:
          claimName: user-session-pvc
---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gotty-terminal-service
  namespace: terminal-app
spec:
  selector:
    app: gotty-terminal
  ports:
    - protocol: TCP
      port: 8080    # Exposed port
      targetPort: 8080  # Container port
  type: ClusterIP


