apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty-terminal
  namespace: sec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty-terminal
  template:
    metadata:
      labels:
        app: gotty-terminal
    spec:
      initContainers:
      - name: init-user
        image: ubuntu:latest  # Use a base image with useradd
        command:
          - /bin/bash
          - -c
          - |
            # Install necessary packages and create user
            apt-get update && apt-get install -y sudo
            # Use the GOTTY_USER environment variable from the ConfigMap
            echo "Creating user ${GOTTY_USER}..."
            useradd -m -s /bin/bash ${GOTTY_USER} && \
            echo "${GOTTY_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${GOTTY_USER} && \
            # Check user creation
            id ${GOTTY_USER} || exit 1
        envFrom:
          - configMapRef:
              name: gotty-config  # Reference the ConfigMap to get GOTTY_USER
        securityContext:
          runAsUser: 0  # Run the init container as root

      containers:
      - name: gotty-terminal
        image: dclinics/sec-labs:v3.46
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gotty-config  # Pass the GOTTY_USER environment variable
        volumeMounts:
        - mountPath: /user_sessions
          name: session-storage
        - mountPath: /etc/sudoers.d
          name: sudoers-volume  # Mount sudoers directory

      volumes:
      - name: session-storage
        persistentVolumeClaim:
          claimName: user-session-pvc
      - name: sudoers-volume
        emptyDir: {}  # Empty directory to mount sudoers directory


---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gotty-terminal-service
  namespace: sec
spec:
  selector:
    app: gotty-terminal
  ports:
    - protocol: TCP
      port: 8080    # Exposed port
      targetPort: 8080  # Container port
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gotty-config
  namespace: sec
data:
  GOTTY_USER: "appuser"  # Replace appuser with your desired username
