apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-server
  labels:
    app: ubuntu-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-server
  template:
    metadata:
      labels:
        app: ubuntu-server
    spec:
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: ubuntu-pvc
        - name: tls-certificates
          hostPath:
            path: "/home/dev/sec-labs/cert" # Path on the Kubernetes node where the certificates are stored
            type: DirectoryOrCreate
      containers:
        - name: sec-labs
          image: dclinics/sec-labs:sh
          ports:
            - containerPort: 22 # SSH port
            - containerPort: 4200 # Web terminal (Shellinabox) port
          volumeMounts:
            - mountPath: /home/users
              name: user-data
            - name: tls-certificates
              mountPath: "/home/dev/sec-labs/cert"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-server-service
  labels:
    app: ubuntu-server
spec:
  selector:
    app: ubuntu-server
  ports:
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22
    - protocol: TCP
      name: web-terminal
      port: 4200
      targetPort: 4200
  type: ClusterIP
