# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotty-ingress
  namespace: terminal-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"


spec:
  # tls:
  # - hosts:
  #   - localhost
  #   secretName: gotty-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gotty-terminal-service
            port:
              number: 8080
