apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubuntu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ubuntu-server-service
                port:
                  number: 80