apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/users
---
# pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-session-pvc
  namespace: terminal-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
