apiVersion: v1
kind: PersistentVolume
metadata:
  name: v3-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/users
---
# pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotty-pvc
  namespace: v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
