apiVersion: v1
kind: Service
metadata:
  name: gotty-backend-service
  namespace: v3
spec:
  selector:
    app: gotty-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000  
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: gotty-frontend-service
  namespace: v3
spec:
  selector:
    app: gotty-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
